apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.102.9:8080"
  restauthenabled: "false"
  gidMin: "40000"
  gidMax: "50000"
  volumetype: "none"

